apiVersion: v1
kind: Service
metadata:
  name: ecsdemo-crystal
  namespace: {{ .Values.ns }}
spec:
  selector:
    app: ecsdemo-crystal
  ports:
   -  protocol: TCP
      port: 80
      targetPort: 3000

